language: elixir
otp_release:
  - 17.4
  - 18.2.1
elixir:
  - 1.1.1
  - 1.2.3
  - 1.3.1
sudo: required
group: edge
services:
  - docker
before_script:
  - docker pull thrift:0.9.3
script:
  - cd $TRAVIS_BUILD_DIR
  - mix compile
  - docker run -v "$PWD:/thrash" -w /thrash thrift:0.9.3 thrift -o src --gen erl test/thrash_test.thrift
  - THRIFT_INPUT_DIR=test/ mix compile.thrift
  - mix test
