language: elixir
matrix:
  include:
    - elixir: 1.1.1
      otp_release: 17.5
    - elixir: 1.2.6
      otp_release: 17.5
    - elixir: 1.2.6
      otp_release: 18.2.1
    - elixir: 1.3.4
      otp_release: 18.2.1
    - elixir: 1.4.5
      otp_release: 18.2.1
    - elixir: 1.4.5
      otp_release: 19.2
    - elixir: 1.5.1
      otp_release: 19.2
    - elixir: 1.5.1
      otp_release: 20.0
sudo: required
group: edge
branches:
  only:
    - "master"
services:
  - docker
before_script:
  - docker pull thrift:0.9.3
script:
  - cd $TRAVIS_BUILD_DIR
  - mix compile
  - THRIFT='docker run -v "$PWD:/thrash" -w /thrash thrift:0.9.3 thrift' THRIFT_INPUT_DIR=test/ mix compile.thrift
  - mix test
