defmodule SimpleStruct do
  # GENERATED by ThriftEx from src/gen-erl/thrash_test_types.hrl

  require Record
  Record.defrecord :simple_struct, :SimpleStruct, 
      [id: :undefined, name: :undefined, list_of_ints: :undefined, bigint: :undefined, sub_struct: :undefined, flag: :undefined, floatval: :undefined, taco_pref: :undefined, list_of_structs: :undefined]

  def record_tag do
    :SimpleStruct
  end

  def struct_info do
    {:struct, [{1, :i32}, {2, :string}, {3, {:list, :i32}}, {4, :i64}, {5, {:struct, {:thrash_test_types, :SubStruct}}}, {6, :bool}, {7, :double}, {8, :i32}, {9, {:list, {:struct, {:thrash_test_types, :SubStruct}}}}]}
  end
end
