defmodule SubStruct do
  # GENERATED by ThriftEx from src/gen-erl/thrash_test_types.hrl

  require Record
  Record.defrecord :sub_struct, :SubStruct, 
      [sub_id: :undefined, sub_name: :undefined]

  def record_tag do
    :SubStruct
  end

  def struct_info do
    {:struct, [{1, :i32}, {2, :string}]}
  end
end
