defmodule ThrashTestConstants do
  # GENERATED by ThriftEx from src/gen-erl/thrash_test_constants.hrl

  def thrash_test_tacotype_chicken do
    126
  end
  
  def thrash_test_tacotype_carnitas do
    124
  end
  
  def thrash_test_tacotype_steak do
    125
  end
  
  def thrash_test_tacotype_pastor do
    127
  end
  
  def thrash_test_tacotype_barbacoa do
    123
  end
  
end